name: ✨ Feature Request
description: Suggest a new feature or enhancement for Dodo Adapters
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand and evaluate your request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you have completed these steps
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have read the documentation to ensure this feature doesn't already exist
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature are you requesting?
      options:
        - "New Framework Adapter"
        - "Core Functionality Enhancement"
        - "Developer Experience Improvement"
        - "Documentation Enhancement"
        - "Testing/Quality Improvement"
        - "Performance Optimization"
        - "Security Enhancement"
        - "Configuration/Setup Improvement"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: package
    attributes:
      label: Affected Package
      description: Which package would this feature affect?
      options:
        - "@dodopayments/core"
        - "@dodopayments/nextjs"
        - "@dodopayments/express"
        - "@dodopayments/fastify"
        - "@dodopayments/hono"
        - "@dodopayments/remix"
        - "@dodopayments/sveltekit"
        - "@dodopayments/astro"
        - "@dodopayments/tanstack"
        - "@dodopayments/nuxt"
        - "@dodopayments/betterauth"
        - "All packages"
        - "New package"
        - "Documentation"
        - "Examples"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What pain point are you experiencing?
      placeholder: |
        Describe the problem you're trying to solve:
        - What are you trying to achieve?
        - What obstacles are you facing?
        - How are you currently working around this?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented?
      placeholder: |
        Describe your ideal solution:
        - What should the feature do?
        - How should it work?
        - What should the API look like?
    validations:
      required: true

  - type: textarea
    id: api_design
    attributes:
      label: API Design (if applicable)
      description: If this feature involves new APIs, what should they look like?
      placeholder: |
        ```typescript
        // Example API design
        export const newFeature = (config: NewFeatureConfig) => {
          // Implementation
        };
        ```
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: |
        What other solutions have you considered?
        - Alternative approach 1
        - Alternative approach 2
        - Why the proposed solution is better
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Critical - Blocking my project"
        - "High - Would significantly improve my workflow"
        - "Medium - Would be nice to have"
        - "Low - Minor improvement"
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe your specific use case
      placeholder: |
        Describe how you would use this feature:
        - What are you building?
        - How would this feature help?
        - What's your expected workflow?
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Examples/References
      description: Any examples from other libraries or frameworks?
      placeholder: |
        References or examples:
        - Similar features in other libraries
        - Links to documentation
        - Code examples from other projects
    validations:
      required: false

  - type: checkboxes
    id: framework_specific
    attributes:
      label: Framework-Specific Requirements
      description: If requesting a new framework adapter, please check applicable requirements
      options:
        - label: Framework is actively maintained
        - label: Framework has TypeScript support
        - label: Framework has significant user base (>1k GitHub stars)
        - label: I can provide example implementation
        - label: I can help with testing

  - type: checkboxes
    id: backward_compatibility
    attributes:
      label: Backward Compatibility
      description: Compatibility considerations
      options:
        - label: This feature should maintain backward compatibility
        - label: Breaking changes are acceptable for this feature
        - label: This could be implemented as an optional feature

  - type: textarea
    id: implementation_notes
    attributes:
      label: Implementation Notes
      description: Any technical considerations or implementation ideas
      placeholder: |
        Technical considerations:
        - Dependencies needed
        - Potential challenges
        - Integration points
        - Testing strategy
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contributing
      description: Would you be willing to help implement this feature?
      options:
        - label: I would be willing to submit a PR to implement this feature
        - label: I can help with testing this feature
        - label: I can help with documentation for this feature

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or information
      placeholder: Add any other context, screenshots, or additional information here
    validations:
      required: false