name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      DODO_PAYMENTS_API_KEY: ${{ secrets.DODO_PAYMENTS_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: rm -rf node_modules package-lock.json && npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: examples/nextjs-basic

      - name: Run CI checks
        run: npm run ci

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: nextjs-example/playwright-report
          path: examples/nextjs-basic/playwright-report/
          retention-days: 30
