name: Release
on:
  release:
    types:
      - published

jobs:
  release-core:
    name: Release @dodopayments/core
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/core
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Verify package
        run: npm pack
      - name: Upload core tarball
        uses: actions/upload-artifact@v4
        with:
          name: core-tarball
          path: packages/core/@dodopayments-core-*.tgz
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}

  release-nextjs:
    name: Release @dodopayments/nextjs
    runs-on: ubuntu-latest
    needs: release-core
    defaults:
      run:
        working-directory: packages/nextjs
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download core tarball
        uses: actions/download-artifact@v4
        with:
          name: core-tarball
          path: ./
      - name: Install core tarball
        run: npm install ../@dodopayments-core-*.tgz
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Verify package
        run: npm pack
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }} 