name: Release
on:
  release:
    types:
      - published

jobs:
  release-core:
    name: Release @dodopayments/core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
        working-directory: packages/core
      - name: Verify package
        run: npm pack
      - name: Publish to NPM
        run: npm publish --access public
        working-directory: packages/core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}

  release-nextjs:
    name: Release @dodopayments/nextjs
    runs-on: ubuntu-latest
    needs: release-core
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
        working-directory: packages/nextjs
      - name: Verify package
        run: npm pack
      - name: Publish to NPM
        run: npm publish --access public
        working-directory: packages/nextjs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }} 